name: Test Action

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Grants permission to request an OIDC token
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - uses: ./ # Use the local action
        with:
          audience: 'tokenbridge'
          tokenbridge-url: ${{ secrets.TOKENBRIDGE_URL }}